data_cfg:
  dataset_name: Xmu_gait
  dataset_root: xxx # modify your path
  dataset_partition: ./datasets/XMUGait.json
  num_workers: 1
  data_in_use: [true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false]
  # [PCD, depth, pcd_fix, gcn, global, joints_location, joints_pose, trans]
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name:  Xmu_gait
  seq_len: 30

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 25000
  save_name: cat7
  eval_func: evaluate_indoor_dataset #evaluate_Gait3D
  sampler:
    batch_shuffle: false
    batch_size: 1
    frames_num_fixed: 16
    sample_type: all_ordered
#    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  transform:
    - type: FromPointsToHeight
    - type: BaseSilTransform
    - type: BaseSilTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true
  - loss_term_weight: 10.0
    type: L1Loss
    log_prefix: l1
    log_accuracy: true
    

model_cfg:
  model: Baseline
  backbone_cfg:
    type: ResNet9
    in_channel: 7
    block: BasicBlock
    channels: # Layers configuration for automatically model construction
      - 64
      - 128
      - 256
      - 512
    layers: 
      - 1
      - 1
      - 1
      - 1
    strides:
      - 1
      - 2
      - 2
      - 1
    maxpool: false
  SeparateFCs:
    in_channels: 512
    out_channels: 256
    parts_num: 16
  SeparateBNNecks:
    class_num: 21
    in_channels: 256
    parts_num: 16
  bin_num:
    - 16

optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 20000
    - 30000
  scheduler: MultiStepLR
trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  with_test: true #true
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 5000
  save_name: cat7
  sync_BN: true
  total_iter: 4000000
  sampler:
    batch_shuffle: true
    batch_size:
      - 8 # TripletSampler, batch_size[0] indicates Number of Identity
      - 8 #                 batch_size[1] indicates Samples sequqnce for each Identity(positive num)
    frames_num_fixed: 30 # fixed frames number for training
    sample_type: fixed_unordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    type: TripletSampler
  transform:
    - type: FromPointsToHeight
    - type: BaseSilTransform
    - type: BaseSilTransform